@preconcurrency import ActivityKit
import AVFoundation
import Foundation

enum VoiceSamplePhase: String {
    case idle
    case listening
    case thinking
    case speaking

    var title: String {
        switch self {
        case .idle: "Voice sample"
        case .listening: "Sameer AI is getting ready"
        case .thinking: "Sameer AI is thinking"
        case .speaking: "Sameer AI is speaking"
        }
    }

    var detail: String {
        switch self {
        case .idle: "A local spoken-response demonstration."
        case .listening: "Preparing a private voice preview. Your microphone is not being used."
        case .thinking: "Preparing the sample reply on this iPhone."
        case .speaking: "This reply is generated by iPhone speech synthesis."
        }
    }

    var activityState: SameerVoiceActivityAttributes.ContentState.SessionState {
        switch self {
        case .idle, .listening: .listening
        case .thinking: .thinking
        case .speaking: .speaking
        }
    }
}

actor VoiceActivityManager {
    private var activity: Activity<SameerVoiceActivityAttributes>?

    func start() throws {
        guard activity == nil else { return }
        let attributes = SameerVoiceActivityAttributes(sessionID: UUID())
        let content: ActivityContent<SameerVoiceActivityAttributes.ContentState> = .init(
            state: SameerVoiceActivityAttributes.ContentState(state: .listening, startedAt: .now),
            staleDate: nil
        )
        activity = try Activity.request(attributes: attributes, content: content)
    }

    func update(to state: SameerVoiceActivityAttributes.ContentState.SessionState) async {
        let content: ActivityContent<SameerVoiceActivityAttributes.ContentState> = .init(
            state: SameerVoiceActivityAttributes.ContentState(state: state, startedAt: .now),
            staleDate: nil
        )
        await activity?.update(content)
    }

    func end() async {
        await activity?.end(nil, dismissalPolicy: .immediate)
        activity = nil
    }
}

@MainActor
final class VoiceSampleController: NSObject, ObservableObject, AVSpeechSynthesizerDelegate {
    @Published private(set) var phase: VoiceSamplePhase = .idle
    @Published private(set) var liveActivityAvailable = true

    private let activityManager = VoiceActivityManager()
    private let synthesizer = AVSpeechSynthesizer()
    private var sequenceTask: Task<Void, Never>?

    override init() {
        super.init()
        synthesizer.delegate = self
    }

    func start() {
        guard phase == .idle else { return }
        phase = .listening
        liveActivityAvailable = true

        do {
            let audioSession = AVAudioSession.sharedInstance()
            try audioSession.setCategory(.playback, mode: .spokenAudio, options: [.duckOthers])
            try audioSession.setActive(true)
        } catch {
            // The on-screen sample remains useful even if another app owns audio.
        }

        Task { [weak self] in
            do {
                try await self?.activityManager.start()
            } catch {
                // The voice sample remains useful if Live Activities are disabled in iOS settings.
                self?.liveActivityAvailable = false
            }
        }

        sequenceTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(1.15))
            guard !Task.isCancelled, let self else { return }
            self.phase = .thinking
            await self.activityManager.update(to: .thinking)

            try? await Task.sleep(for: .seconds(0.8))
            guard !Task.isCancelled else { return }
            self.phase = .speaking
            await self.activityManager.update(to: .speaking)

            let reply = AVSpeechUtterance(string: "Hello Sameer. This is the private Sameer AI voice sample. The final version will use your selected on-device model.")
            reply.voice = AVSpeechSynthesisVoice(language: "en-US")
            reply.rate = AVSpeechUtteranceDefaultSpeechRate * 0.92
            self.synthesizer.speak(reply)
        }
    }

    func stop() {
        sequenceTask?.cancel()
        sequenceTask = nil
        synthesizer.stopSpeaking(at: .immediate)
        finish()
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        Task { @MainActor [weak self] in self?.finish() }
    }

    private func finish() {
        guard phase != .idle else { return }
        sequenceTask?.cancel()
        sequenceTask = nil
        phase = .idle
        try? AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
        Task { await activityManager.end() }
    }
}
